spring:
  application:
    name: apollo-demo
server:
  port: 9101
#Apollo 配置
app:
  id: apollo-demo  #应用ID
apollo:
  access-key:
    secret: 9b2c19c72bfb4e1185c1e1be6d39c14b
  cacheDir: C:\opt\data\{appId}\config-cache #配置本地配置缓存目录
  cluster: default                           #指定使用哪个集群的配置
  meta: http://ec-alpha.apollo.casstime.com:8080      #DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                            #是否开启 Apollo
    namespaces: application                  #设置 Namespace
    eagerLoad:
      enabled: false                         #将 Apollo 加载提到初始化日志系统之前

