server:
  port: 8901
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://gitlab.casstime.net/a02918/infra-configuration.git
          username: A02918
          password: Geilidaxue2
          clone-on-start: true #开启启动时直接从git获取配置
          search-paths: config,commons,infra
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/