server:
  port: 8901
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://gitlab.xxx.net/xxx/infra-configuration.git
          username: xxx
          password: xxx
          clone-on-start: true #开启启动时直接从git获取配置
          search-paths: config,commons,infra
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/